config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # GET http://localhost:3000/restaurants/new
  get "/restaurants/new", to: "restaurants#new", as: "new_restaurant"

  # POST http://localhost:3000/restaurants
  post "/restaurants",    to: "restaurants#create"

  # GET http://localhost:3000/restaurants
  get "/restaurants",     to: "restaurants#index"

  # GET http://localhost:3000/restaurants/4
  # GET http://localhost:3000/restaurants/2
  get "/restaurants/:id", to: "restaurants#show", as: "restaurant"

  # GET http://localhost:3000/restaurants/1/edit
  get "/restaurants/:id/edit", to: "restaurants#edit", as: "edit_restaurant"

  # PATCH http://localhost:3000/restaurants/1
  patch "/restaurants/:id",    to: "restaurants#update"

  # DELETE http://localhost:3000/restaurants/1
  delete "/restaurants/:id",   to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [ :show, :edit, :update, :destroy ]

    def index
        # fetch all restaurants
        @restaurants = Restaurant.all
    end

    def show
        # find a restaurant by id
        # set_restaurant()
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        # create == new + save
        @restaurant = Restaurant.create(restaurant_params)

        redirect_to restaurant_path(@restaurant), notice: "Thanks for creating!"
    end

    def edit
        # find the given restaurant by id
        # set_restaurant()
    end

    def update
        # find the given restaurant by id
        # update the attributes
        # set_restaurant()
        @restaurant.update(restaurant_params)

        redirect_to restaurant_path(@restaurant.id)
    end

    def destroy
        # find the given restaurant by id
        # delete it
        # set_restaurant()
        @restaurant.destroy

        redirect_to restaurants_path, status: :see_other
    end

    private

    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
        # strong params (manually & specifically permit parameters)
        params.require(:restaurant).permit(:name, :address, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: @restaurant do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :rating %>
    <%= f.number_field :rating %>

    <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<%= render "form" %>
<%= link_to "< Go back", restaurant_path(@restaurant) %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<%# <ul>
    <li>rest 1</li>
    <li>rest 2</li>
    <li>rest 3</li>
</ul> %>

<ul>
    <% @restaurants.each do |resto| %>
        <%#= link_to "text the user sees", destination_path %>
        <li><%= link_to resto.name, restaurant_path(resto.id) %></li>
    <% end %>
</ul>

<%= link_to "Add restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add new restaurant</h1>

<%= render "form" %>

<%= link_to "< Back", restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Details about <%= @restaurant.name %></h1>
<p>Address: <%= @restaurant.address %></p>
<p><%= "*" * @restaurant.rating%></p>

<%= link_to "Edit restaurant", edit_restaurant_path(@restaurant.id) %>
<br>
<%= link_to "Delete restaurant", 
    restaurant_path(@restaurant.id), 
    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } 
%>
<br>
<%= link_to "< Back", restaurants_path %>